version: "3.8"

services:
  spring:
    build: app/.
    container_name: cve-2021-44228
    image: ahmad4fifz/cve-2021-44228
    networks:
      - cve-2021-44228
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - ./data:/app

networks:
  cve-2021-44228:
    name: cve-2021-44228