apiVersion: v1
kind: Pod
metadata:
  labels:
    app: cve-2021-44228-pod
  name: cve-2021-44228-pod
spec:
  containers:
  - command:
    - java
    - -jar
    - /app.jar
    env:
    - name: PATH
      value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/jvm/java-1.8-openjdk/jre/bin:/usr/lib/jvm/java-1.8-openjdk/bin
    - name: TERM
      value: xterm
    - name: JAVA_ALPINE_VERSION
      value: 8.212.04-r0
    - name: LANG
      value: C.UTF-8
    - name: JAVA_HOME
      value: /usr/lib/jvm/java-1.8-openjdk
    - name: JAVA_VERSION
      value: 8u212
    image: localhost/ahmad4fifz/cve-2021-44228
    name: cve-2021-44228
    ports:
    - containerPort: 8080
      hostPort: 8080
      hostIP: 0.0.0.0
      protocol: TCP
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
      privileged: false
      readOnlyRootFilesystem: false
      runAsGroup: 101
      runAsUser: 100
      seLinuxOptions: {}
    tty: true
    workingDir: /
  dnsConfig: {}
  restartPolicy: OnFailure
status: {}